import dataclasses
import logging
import pickle
import traceback
from pathlib import Path

import flask
import numpy as np
import torch
import tyro
from flask import jsonify, request
from hydra.utils import instantiate
from omegaconf import OmegaConf

from il_lib.utils.training_utils import load_state_dict, load_torch

app = flask.Flask(__name__)
_POLICY = None
_DEVICE = "cuda"


@dataclasses.dataclass
class Args:
    # ACT arch config (defaults to the custom OpenFridge config).
    arch_config: str = "il_lib/configs/arch/act_openfridge.yaml"
    # Checkpoint path generated by il_lib training.
    ckpt_path: str = ""
    # Default prompt passed by client when prompt is missing.
    prompt: str = "move to the fridge, then open the door"
    host: str = "0.0.0.0"
    port: int = 8000
    device: str = "cuda"
    # Fallback lr for ACT init when arch-only config has no lr field.
    lr: float = 1e-4


# Accept both OpenPI-style keys and raw camera keys from simulator.
CAMERA_KEY_MAP = {
    "base_0_rgb": "observation.images.first_person_camera",
    "left_wrist_0_rgb": "observation.images.left_hand_camera",
    "right_wrist_0_rgb": "observation.images.right_hand_camera",
    "first_person_camera": "observation.images.first_person_camera",
    "left_hand_camera": "observation.images.left_hand_camera",
    "right_hand_camera": "observation.images.right_hand_camera",
    "observation.images.first_person_camera": "observation.images.first_person_camera",
    "observation.images.left_hand_camera": "observation.images.left_hand_camera",
    "observation.images.right_hand_camera": "observation.images.right_hand_camera",
}


def _load_policy(args: Args) -> None:
    global _POLICY, _DEVICE
    _DEVICE = args.device

    if not args.ckpt_path:
        raise ValueError("--ckpt_path is required")

    arch_cfg_path = Path(args.arch_config)
    if not arch_cfg_path.exists():
        raise FileNotFoundError(f"arch config not found: {arch_cfg_path}")

    ckpt = load_torch(args.ckpt_path, map_location="cpu")
    cfg = OmegaConf.load(arch_cfg_path)
    # ACT.__init__ requires lr. Training config usually injects this from base_config;
    # here we serve from arch-only config, so we fill it from checkpoint hparams or fallback.
    if "module" not in cfg:
        raise ValueError(f"Invalid arch config: missing 'module' in {arch_cfg_path}")
    if "lr" not in cfg.module:
        ckpt_hparams = ckpt.get("hyper_parameters", {})
        cfg.module.lr = float(ckpt_hparams.get("lr", args.lr))
    OmegaConf.resolve(cfg)
    policy = instantiate(cfg.module, _recursive_=False)

    load_state_dict(policy, ckpt["state_dict"], strict=True)
    policy = policy.to(_DEVICE)
    policy.eval()
    _POLICY = policy

    print(f"[ACT-Server] loaded ckpt: {args.ckpt_path}")
    print(f"[ACT-Server] using device: {_DEVICE}")


def _prepare_obs(images: dict, state: np.ndarray) -> dict:
    obs = {}

    s = torch.from_numpy(np.asarray(state, dtype=np.float32))
    if s.ndim == 1:
        s = s.unsqueeze(0).unsqueeze(0)  # (1, 1, D)
    elif s.ndim == 2:
        s = s.unsqueeze(0)  # (1, T, D)
    obs["state"] = s.to(_DEVICE)

    for in_key, img in images.items():
        if in_key not in CAMERA_KEY_MAP:
            continue
        model_cam_key = CAMERA_KEY_MAP[in_key]

        img_np = np.asarray(img)
        if img_np.ndim == 3 and img_np.shape[-1] == 4:
            img_np = img_np[..., :3]
        if img_np.dtype != np.uint8:
            if np.issubdtype(img_np.dtype, np.floating):
                img_np = np.clip(img_np, 0.0, 1.0)
                img_np = (img_np * 255.0).astype(np.uint8)
            else:
                img_np = img_np.astype(np.uint8)
        if img_np.ndim != 3:
            raise ValueError(f"Invalid image shape for {in_key}: {img_np.shape}")

        img_chw = torch.from_numpy(img_np).permute(2, 0, 1).contiguous()  # (C,H,W)
        img_chw = img_chw.unsqueeze(0).unsqueeze(0).to(_DEVICE)  # (1,1,C,H,W)
        obs[f"{model_cam_key}::rgb"] = img_chw

    if not any(k.endswith("::rgb") for k in obs):
        raise ValueError("No valid camera image found in request payload.")

    return {"obs": obs}


@app.route("/health", methods=["GET"])
def health():
    return "OK", 200


@app.route("/infer", methods=["POST"])
def infer():
    global _POLICY
    try:
        if _POLICY is None:
            return jsonify({"error": "policy not loaded"}), 500

        data = pickle.loads(request.data)
        images = data.get("images", {})
        state = np.asarray(data.get("state"), dtype=np.float32)

        obs = _prepare_obs(images, state)
        with torch.no_grad():
            action = _POLICY.act(obs)  # (1, T, A)
        action_np = np.asarray(action)

        return pickle.dumps({"actions": action_np})
    except Exception as e:
        traceback.print_exc()
        return jsonify({"error": str(e), "trace": traceback.format_exc()}), 500


def main(args: Args):
    _load_policy(args)
    print(f"[ACT-Server] serving on http://{args.host}:{args.port}")
    app.run(host=args.host, port=args.port, threaded=False, debug=False)


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    main(tyro.cli(Args))
