# @package _global_

arch_name: act_openfridge

# ====== Policy specific ======
num_latest_obs: 1
horizon: 20
deployed_action_steps: 1
wd: 0.1
bs: 64

module:
  _target_: il_lib.policies.ACT
  prop_dim: 25
  prop_keys:
    - state
  action_dim: 25
  action_keys:
    - action
  features: [rgb]
  obs_backbone:
    _target_: il_lib.nn.features.MultiviewResNet18
    backbone: resnet18
    views:
      - observation.images.first_person_camera
      - observation.images.left_hand_camera
      - observation.images.right_hand_camera
    resnet_output_dim: 512
    use_shared_backbone: true
    load_pretrained: true
    include_depth: false
    enable_random_crop: true
    random_crop_size: 224
    return_last_spatial_map: true
  pos_encoding:
    position_embedding: sine
    hidden_dim: ${module.hidden_dim}
  num_queries: ${horizon}
  hidden_dim: 512
  dropout: 0.1
  n_heads: 8
  dim_feedforward: 3200
  num_encoder_layers: 4
  num_decoder_layers: 7
  pre_norm: false
  kl_weight: 10
  temporal_ensemble: true

data:
  dataset_class: il_lib.datas.LeRobotACTDataset
  use_action_chunks: false
  visual_obs_types: [rgb]
